{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Apertura del archivo \"Plantilla Real a Liquidar Transporte\" creación del dataframe \"FLETES\"y su depuración"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL72 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL73 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL74 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL75 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL76 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL77 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL78 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL79 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL236 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL237 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL238 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL239 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL255 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL256 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL257 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL540 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL541 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL542 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL543 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL544 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL545 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL546 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL547 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL548 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL549 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL550 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL551 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL552 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL553 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL554 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL555 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL556 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL557 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL558 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL559 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL560 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL561 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL562 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL563 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL564 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL565 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL566 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL567 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL568 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell Y569 is marked as a date but the serial value 3175137229 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL569 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL570 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL571 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell Y572 is marked as a date but the serial value 3175137229 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL572 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL573 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL574 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL575 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL576 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL577 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL578 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL579 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL580 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL581 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL582 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL583 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL584 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell Y585 is marked as a date but the serial value 3175137229 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL585 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL941 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL942 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL943 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL944 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL967 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL968 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL977 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1174 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1175 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1176 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1177 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1178 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1179 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1180 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1181 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1182 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1183 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1184 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1185 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1186 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1187 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1188 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1189 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1190 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1191 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1192 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1193 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1249 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1250 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1251 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1252 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1253 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1269 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1270 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1707 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1708 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1709 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1710 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1975 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1976 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1977 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1978 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1979 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1980 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1981 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1982 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1983 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1984 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1985 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1986 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1987 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1988 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1989 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL1990 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2121 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2122 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2123 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2124 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2125 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2126 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2127 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2128 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2129 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2149 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2150 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2151 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2152 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2153 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2154 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2155 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2156 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2157 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2158 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2159 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2160 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2161 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2162 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2163 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2193 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2194 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2195 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2196 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2197 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2200 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2201 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2202 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2203 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2204 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2205 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2206 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2207 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2208 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2209 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2210 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2211 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2212 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2213 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2245 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2246 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2247 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2248 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2249 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2250 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2251 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2256 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2270 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2271 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2272 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2297 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2298 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2299 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2300 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2301 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2302 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2303 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2304 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2305 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2306 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2307 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2308 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2309 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2310 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2311 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2312 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2313 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2314 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2315 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2316 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2317 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2422 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2423 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2424 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2425 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2426 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2427 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2428 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2429 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2430 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2431 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2432 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2433 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2434 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2435 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2436 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2437 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell Y2699 is marked as a date but the serial value 3183490254 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell Y2700 is marked as a date but the serial value 3183490254 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell Y2715 is marked as a date but the serial value 3167535929 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell Y2716 is marked as a date but the serial value 3167535929 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell Y2717 is marked as a date but the serial value 3023254307 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell Y2718 is marked as a date but the serial value 3023254307 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell Y2719 is marked as a date but the serial value 3104373272 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell Y2720 is marked as a date but the serial value 3104373272 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell Y2737 is marked as a date but the serial value 3104269211 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell Y2738 is marked as a date but the serial value 3104269211 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2801 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell AL2802 is marked as a date but the serial value 901623528 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell Y2978 is marked as a date but the serial value 3023684392 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell Y2979 is marked as a date but the serial value 3023684392 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell Y2980 is marked as a date but the serial value 3023684392 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell Y2981 is marked as a date but the serial value 3023684392 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell Y2982 is marked as a date but the serial value 3023684392 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell Y3091 is marked as a date but the serial value 3163522463 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell Y3092 is marked as a date but the serial value 3163522463 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell Y3096 is marked as a date but the serial value 3166184304 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell Y3097 is marked as a date but the serial value 3166184304 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell Y3159 is marked as a date but the serial value 3162982821 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n",
      "c:\\Users\\RentAdvisor\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\openpyxl\\worksheet\\_reader.py:223: UserWarning: Cell Y3160 is marked as a date but the serial value 3162982821 is outside the limits for dates. The cell will be treated as an error.\n",
      "  warn(msg)\n"
     ]
    }
   ],
   "source": [
    "# importarción de librerias que se van a utilizar.\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "# definición del path del archivo y la hoja la cual se va a traer y depurar.\n",
    "str_ruta = r'C:\\Users\\RentAdvisor\\Bot2-Eficacia\\Archivos Base\\PLANTILLA REAL A LIQUIDAR  TRANSPORTES FINAL.xlsx'\n",
    "str_nombre_hoja = 'FLETES'\n",
    "\n",
    "# creación del dataframe de la hoja \"FLETES\"\n",
    "df_fletes = pd.read_excel(str_ruta, sheet_name=str_nombre_hoja)\n",
    "\n",
    "# Depuración de las columnas para eliminar valores invalidos\n",
    "columnas_tipo_texto = ['punto', 'tipo_despacho', 'pedido', 'identificacion', 'contacto', 'nombre_completo', 'nombre_ciudad', 'codigo_flete', 'usuario_pedido', 'dato_adicional_pedido', 'articulos', 'documentos1', 'documentos2', 'tipo_ubicacion', 'placa', 'nombre_conductor', 'transportador', 'nombre_transportador', 'clasificador1', 'soporte', 'proveedor', 'usuario_insercion', 'CONCATENAR PESO,PROVEEDOR ', 'CIUDA', 'DEPARTAMENTO', 'PUNTO ORIGEN ', 'RANGO VOLUMEN', 'RANGOPESO ', 'PESO COTIZADO ', 'VOLUMEN COTIZADO ']\n",
    "columnas_tipo_numero = ['entrega', 'despacho', 'salida', 'codigo', 'departamento', 'ciudad', 'ruta_terrestre', 'total_peso', 'total_volumen', 'peso_cotizado', 'volumen_cotizado', 'cajas_cotizado', 'valor_mercancia', 'tiempo_real', 'demora', 'numero_guia']\n",
    "\n",
    "for columna in columnas_tipo_texto:\n",
    "    df_fletes[columna] = df_fletes[columna].fillna(\"\")\n",
    "\n",
    "for columna in columnas_tipo_numero:\n",
    "    df_fletes[columna] = pd.to_numeric(df_fletes[columna], errors='coerce').replace(np.nan, 0, regex=True)\n",
    "\n",
    "# Creación de nueva columna y conversión de la columna de \"fecha_entrega\" con formato fecha con hora a nueva columna \"fecha_entrega_dia\" con formato año-mes-día\n",
    "df_fletes['fecha_entrega_dia'] = df_fletes['fecha_entrega'].dt.date\n",
    "\n",
    "# Creación de nuevas columnas necesarias dentro del dataframe\n",
    "df_fletes['tipo']=\"\"\n",
    "df_fletes['tipo_ruta']=\"\"\n",
    "df_fletes['validacion_24h']=\"\"\n",
    "df_fletes['valor_bot']=\"\"\n",
    "df_fletes['valor_original_bot']=\"\""
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Creación de dataframes con valores estandares"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "# definición de las hojas que serán traidas.\n",
    "str_nombre_hoja2 = 'TIPO RUTA'\n",
    "str_nombre_hoja3 = 'TARIFA CLIENTE'\n",
    "str_nombre_hoja4 = 'TARIFA PROVEEDOR'\n",
    "str_nombre_hoja5 = 'TARIFA P y V'\n",
    "str_nombre_hoja6 = 'CODIGO FLETE'\n",
    "\n",
    "# creación de los dataframes con valores estandarizados que serán necesarios.\n",
    "df_tipo_ruta = pd.read_excel(str_ruta, sheet_name=str_nombre_hoja2)\n",
    "df_tarifa_cliente = pd.read_excel(str_ruta, sheet_name=str_nombre_hoja3)\n",
    "df_tarifa_proveedor = pd.read_excel(str_ruta, sheet_name=str_nombre_hoja4)\n",
    "df_tarifa_pv = pd.read_excel(str_ruta, sheet_name=str_nombre_hoja5)\n",
    "df_codigo_flete = pd.read_excel(str_ruta, sheet_name=str_nombre_hoja6)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Asignación de tipo de ruta a la columna \"tipo_ruta\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Definición de todos las filas con la palabra \"PERIFERIA\"\n",
    "df_fletes['tipo_ruta'] = 'PERIFERIA'\n",
    "\n",
    "# Iteración a través de las filas del dataframe df_fletes y comparación con el dataframe df_tipo_ruta\n",
    "for i, fila in df_fletes.iterrows():\n",
    "    punto = fila['punto']\n",
    "    ciudad = fila['nombre_ciudad']\n",
    "    \n",
    "    # Verificación de coincidencias en df_tipo_ruta y asignación de la palabra \"LOCAL\" en las filas necesarias\n",
    "    if any((df_tipo_ruta['CEDIS'] == punto) & (df_tipo_ruta['CIUDAD'] == ciudad)):\n",
    "        df_fletes.at[i, 'tipo_ruta'] = 'LOCAL'"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Agrupación de datos para rutas locales de tipo despacho y recogida"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'for indice, datos in df_grupo_locales:\\n  print(\"....indice={}\".format(indice))\\n  print(\"--------datos-------\")\\n  print(datos)'"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Creación de grupos por respectivos filtros para despachos y recogidas\n",
    "filtro = (df_fletes['tipo_ruta'] == 'LOCAL') & ((df_fletes['tipo_despacho'] == 'DESPACHO') | (df_fletes['tipo_despacho'] == 'RECOGIDA'))\n",
    "df_dr_locales = df_fletes[filtro].groupby(['punto', 'fecha_entrega', 'proveedor', 'identificacion'])\n",
    "\n",
    "\n",
    "# Tipos de despachos que hay por cada una de las agrupaciones\n",
    "valores_unicos_despachos = df_dr_locales['tipo_despacho'].apply(lambda x: x.unique())\n",
    "\n",
    "############ Descomentar si se desea ver los grupos ################\n",
    "\"\"\"for indice, datos in df_grupo_locales:\n",
    "  print(\"....indice={}\".format(indice))\n",
    "  print(\"--------datos-------\")\n",
    "  print(datos)\"\"\"\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Clasificación de cada grupo por tipo de despacho"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Conversión de los tipos de despacho por grupo a un dataframe para su mejor manipulación\n",
    "df_tipo_liquidar = valores_unicos_despachos.to_frame(name='tipo')\n",
    "\n",
    "# Creación de nueva columna dentro del dataframe df_tipo_grupo_ruta\n",
    "df_tipo_liquidar[\"tipo_grupo_ruta\"] = \"\"\n",
    "df_tipo_liquidar[\"numero_despachos\"] = \"\"\n",
    "df_tipo_liquidar[\"transportador\"] = \"\"\n",
    "df_tipo_liquidar['codigos_flete'] = \"\"\n",
    "\n",
    "# Función para clasasificar los grupos por tipos de despacho\n",
    "def asignar_valor(row):\n",
    "    if set(row['tipo']) == set(['DESPACHO']):\n",
    "        return 1\n",
    "    elif set(row['tipo']) == set(['RECOGIDA']):\n",
    "        return 2\n",
    "    elif set(row['tipo']) == set(['RECOGIDA','DESPACHO']):\n",
    "        return 3\n",
    "    else:\n",
    "        return 0\n",
    "\n",
    "# Asignación de la clasificación a la columna \"tipo_grupo_ruta\" dentro del dataframe df_tipo_grupo_ruta \n",
    "df_tipo_liquidar['tipo_grupo_ruta'] = df_tipo_liquidar.apply(asignar_valor, axis=1)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Conteo de despachos por agrupación\n",
    "conteo_despacho = df_dr_locales['despacho'].agg(lambda x: x.nunique())\n",
    "conteo_a_lista = conteo_despacho.tolist()\n",
    "\n",
    "# Asignación de conteo a DataFrame \"df_tipo_grupo_ruta\"\n",
    "df_tipo_liquidar['numero_despachos'] = conteo_a_lista\n",
    "\n",
    "# Valor de transportador por despacho\n",
    "valores_transportador = df_dr_locales['transportador'].apply(lambda x: x.unique())\n",
    "valores_a_lista = valores_transportador.tolist()\n",
    "\n",
    "# Asignación de valores a DataFrame \"df_tipo_grupo_ruta\"\n",
    "df_tipo_liquidar['transportador'] = valores_a_lista\n",
    "\n",
    "# Valores de código de flete por despacho cada despacho\n",
    "valores_codigo_flete = df_dr_locales['codigo_flete'].apply(lambda x: x.unique())\n",
    "valores_codigo_a_lista = valores_codigo_flete.tolist()\n",
    "\n",
    "# Asignación de valores a DataFrame \"df_tipo_grupo_ruta\"\n",
    "df_tipo_liquidar['codigos_flete'] = valores_codigo_a_lista\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Detectar y cambiar campos en blanco"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Campos en blanco en la columna 'codigo_flete':\n",
      "   codigo_flete                                             nombre      valor  \\\n",
      "0      NO_OFREC                                        NO_OFRECIDO       0.00   \n",
      "1      ZONARIES                                        ZONA RIESGO       0.20   \n",
      "2        ESPERA                                    FRACCION ESPERA       0.30   \n",
      "3       EXPRESO                                            EXPRESO       0.35   \n",
      "4       REDONDO                                            REDONDO       0.50   \n",
      "5        ERRADA                                   DIRECCION ERRADA       1.00   \n",
      "6      2DO_OFRE                               SEGUNDO OFRECIMIENTO       1.00   \n",
      "7       FALLIDO                      ENTREGA NO EFECTIVA - FALLIDA       1.00   \n",
      "8      CARROLLE                                        CARRO LLENO       1.50   \n",
      "9         M1-25  MUEBLE CATEGORIA UNO ENTRE 1 A 25 KILOS O ( 1....       0.50   \n",
      "10     1P-100KG                     1 POSICION ENTRE 0 A 100 KILOS       0.50   \n",
      "11     M2-26-50  MEUBLE CATEGORIA DOS ENTRE 26 A 50 KILOS O 2 P...       1.00   \n",
      "12     2P-1C-2C                     2 POSICIONES 100 O = 200 KILOS       1.00   \n",
      "13     3P-2C-3C                     3 POSICIONES 200 O = 300 KILOS       1.50   \n",
      "14     M3-26-1C  MUEBLE CATEGORIA TRES ENTRE 26 A 100 KILOS O 3...       2.00   \n",
      "15     4P-3C-4C                     4 POSICIONES 300 O = 400 KILOS       2.00   \n",
      "16     5P-4C-5C                     5 POSICIONES 400 O = 500 KILOS       2.50   \n",
      "17     M4-1C-2C  MUEBLE CATEGORIA CUATRO ENTRE 100 A 500 KILOS ...       3.00   \n",
      "18     6P-5C-6C                     6 POSICIONES 500 O = 600 KILOS       3.00   \n",
      "19     7P-6C-7C                     7 POSICIONES 600 O = 700 KILOS       3.50   \n",
      "20     8P-7C-8C                     8 POSICIONES 700 O = 800 KILOS       4.00   \n",
      "21     9P-8C-9C                     9 POSICIONES 800 O = 900 KILOS       4.50   \n",
      "22       10P-1T                   10 POSICIONES 900 O = 1000 KILOS       5.00   \n",
      "23       MASIVO                         MASIVO ENTREGAS NACIONALES       0.00   \n",
      "24     EX-CARRY          VEHICULO EXCLUSIVO TIPO CARRY HASTA 500KG   90000.00   \n",
      "25     EXCLU-1T                   VEHICULO EXCLUSIVO DE 1 TONELADA  140000.00   \n",
      "26     EXCLU-2T                  VEHICULO EXCLUSIVO DE 2 TONELADAS  160000.00   \n",
      "27       EX-TRB             VEHICULO EXCLUSIVO TURBO 4.5 TONELADAS  350000.00   \n",
      "28      DESCARG                                          DESCARGUE   35000.00   \n",
      "29       EX-SEN            VEHICULO EXCLUSIVO SENCILLO 8 TONELADAS  570000.00   \n",
      "30      AUXILIO                                    AUXILIO GESTION   25000.00   \n",
      "31      1-AUXIL                   1 AUXILIAR DE CARGUE Y DESCARGUE   50000.00   \n",
      "32      2-AUXIL                   2 AUXILIAR DE CARGUE Y DESCARGUE  100000.00   \n",
      "33      3-AUXIL                   3 AUXILIAR DE CARGUE Y DESCARGUE  150000.00   \n",
      "34      4-AUXIL                   4 AUXILIAR DE CARGUE Y DESCARGUE  200000.00   \n",
      "\n",
      "   tipo  \n",
      "0     P  \n",
      "1     P  \n",
      "2     P  \n",
      "3     P  \n",
      "4     P  \n",
      "5     P  \n",
      "6     P  \n",
      "7     P  \n",
      "8     P  \n",
      "9     P  \n",
      "10    P  \n",
      "11    P  \n",
      "12    P  \n",
      "13    P  \n",
      "14    P  \n",
      "15    P  \n",
      "16    P  \n",
      "17    P  \n",
      "18    P  \n",
      "19    P  \n",
      "20    P  \n",
      "21    P  \n",
      "22    P  \n",
      "23    V  \n",
      "24    V  \n",
      "25    V  \n",
      "26    V  \n",
      "27    V  \n",
      "28    V  \n",
      "29    V  \n",
      "30    V  \n",
      "31    V  \n",
      "32    V  \n",
      "33    V  \n",
      "34    V  \n"
     ]
    }
   ],
   "source": [
    "\n",
    "# Detectar campos en blanco (NaN) en la columna \"codigo_flete\"\n",
    "campos_en_blanco = df_codigo_flete['codigo_flete'].isna() \n",
    "\n",
    "# Verifica si el valor de \"codigo_flete\" es \"LOCAL\" o en blanco (NaN)\n",
    "expected = (df_codigo_flete['codigo_flete'].isna()) | (df_codigo_flete['codigo_flete'] == \"LOCAL\")\n",
    "\n",
    "# Imprimir información sobre campos en blanco en la columna \"codigo_flete\"\n",
    "print(\"Campos en blanco en la columna 'codigo_flete':\")\n",
    "\n",
    "# Rellena los campos en blanco con \"Sin valor\" solo si la condición se cumple\n",
    "df_codigo_flete.loc[expected, 'codigo_flete'] = \"Sin valor\"\n",
    "\n",
    "# Imprimir el DataFrame \n",
    "print(df_codigo_flete)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Copiar y mover los valores de \"valor\" y \"calor_original\" a las nuevas columnas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Changes in 'valor_bot' column:\n",
      "     valor valor_bot\n",
      "585    NaN       NaN\n",
      "652    NaN       NaN\n",
      "947    NaN       NaN\n",
      "1733   NaN       NaN\n",
      "2598   NaN       NaN\n",
      "2600   NaN       NaN\n",
      "2602   NaN       NaN\n",
      "2604   NaN       NaN\n",
      "2606   NaN       NaN\n",
      "Changes in 'valor_original_bot' column:\n",
      "     valor_original valor_original_bot\n",
      "553             NaN                NaN\n",
      "585             NaN                NaN\n",
      "652             NaN                NaN\n",
      "3077            NaN                NaN\n"
     ]
    }
   ],
   "source": [
    "# Copiar los valores de \"valor\" y \"valor_original\"\n",
    "df_fletes['valor_bot'] = df_fletes['valor']\n",
    "df_fletes['valor_original_bot'] = df_fletes['valor_original']\n",
    "\n",
    "# Comparar los valores de las dos columnas\n",
    "changed_valor_bot = df_fletes[df_fletes['valor'] != df_fletes['valor_bot']]\n",
    "changed_valor_original_bot = df_fletes[df_fletes['valor_original'] != df_fletes['valor_original_bot']]\n",
    "\n",
    "# Imprimir el Dataframe con los cambis\n",
    "print(\"Changes in 'valor_bot' column:\")\n",
    "print(changed_valor_bot[['valor', 'valor_bot']])\n",
    "\n",
    "print(\"Changes in 'valor_original_bot' column:\")\n",
    "print(changed_valor_original_bot[['valor_original', 'valor_original_bot']])\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "  codigos_flete  tipo_grupo_ruta  valor  resultado\n",
      "0         LOCAL                1    100        NaN\n",
      "1          TCOD                2    200      200.0\n",
      "2         LOCAL                1    150        NaN\n",
      "3        MASIVO                2    300        0.0\n",
      "4          TCOD                1    120      120.0\n"
     ]
    }
   ],
   "source": [
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "# Data de muestra\n",
    "data = {\n",
    "    'codigos_flete': ['LOCAL', 'TCOD', 'LOCAL', 'MASIVO', 'TCOD'],\n",
    "    'tipo_grupo_ruta': [1, 2, 1, 2, 1],\n",
    "    'valor': [100, 200, 150, 300, 120]\n",
    "}\n",
    "\n",
    "# Marco de data de muestra \n",
    "df_tipo_liquidar = pd.DataFrame(data)\n",
    "\n",
    "# Definir variable numero_despachos(modificar a la actual)\n",
    "numero_despachos = 10  \n",
    "\n",
    "# Definir la función calcular_prueba_funcion\n",
    "def calcular_prueba_funcion(row):\n",
    "    codigos_flete = row[\"codigos_flete\"]\n",
    "    tipo_grupo_ruta = row[\"tipo_grupo_ruta\"]\n",
    "    valor_cliente = row['valor']\n",
    "\n",
    "# Comprobar si codigos_flete es un ndarray 1D y contiene un solo valor, que sea 'LOCAL'\n",
    "    if isinstance(codigos_flete, np.ndarray) and len(codigos_flete) == 1 and 'LOCAL' in codigos_flete:\n",
    "        if tipo_grupo_ruta in [1, 2]:\n",
    "            return round(valor_cliente / numero_despachos)\n",
    "        else:\n",
    "            return 0\n",
    "    elif 'TCOD' in codigos_flete:\n",
    "        return valor_cliente\n",
    "    elif 'MASIVO' in codigos_flete:\n",
    "        return 0\n",
    "    else:\n",
    "        return None\n",
    "\n",
    "# Aplicar la función a cada fila del DataFrame y crear una nueva columna \"resultado\"\n",
    "df_tipo_liquidar['resultado'] = df_tipo_liquidar.apply(calcular_prueba_funcion, axis=1)\n",
    "\n",
    "# Imprime el DataFrame resultante con la columna \"resultado\"\n",
    "print(df_tipo_liquidar)\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
